#!/usr/bin/env python3
"""Serialize the SSOP decision ontology to OWL (Turtle) — Phase 1 of the
formal-ontology roadmap (operator 2026-09-10, ref aws/context-ontology-
accelerator vocabulary adoption).

GENERATED, not hand-edited: categories come from tools/ontology.py's
taxonomy, roles from docs/roles/README.md's role map, tiers/approval
semantics from the code as documented in docs/roles/responder.md. Run this
after changing any of those; the artifact is the machine-readable statement
of the decision model. Phase 2 (reasoner consistency gates) consumes this.

Output: docs/ontology/ssop.ttl (Turtle). No owlready2 required at build
time — hand-emitted Turtle keeps the export dependency-free; owlready2 is
only needed when the reasoner runs (Phase 2).

Usage: python3 agents/tools/ontology_export.py [--check]
  --check: exit 1 if the on-disk artifact differs from a fresh render
           (drift gate — pair with check_docs).
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
OUT = REPO / "docs" / "ontology" / "ssop.ttl"

PREFIXES = """@prefix : <http://ssop.local/ontology#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
"""

# The alert-category taxonomy — mirrored from tools/ontology.py
# categorize_alert() (single source of truth). If a category is added
# there, add it here; check_ontology (phase 2) will cross-verify.
CATEGORIES = [
    ("authentication", "Authentication events (logins, auth failures, "
     "session anomalies). Escalates at medium severity unless pure "
     "brute-force noise."),
    ("threat", "Attack-class events (ET MALWARE signatures, C2, exfil, "
     "malware dns). Escalates even at low level — the indicator is the "
     "signal, not Wazuh's level mapping."),
    ("integrity", "File-integrity / rootcheck / syscheck events (FIM). "
     "Escalates only at category-high level (12) — routine scans are "
     "maintenance."),
    ("compliance", "Policy / SCA / vulnerability events."),
    ("operational", "Routine system events (sessions, services, dpkg) — "
     "no dispatch by default."),
    ("infra", "Fleet-health events (disk, systemd service health, sudo) — "
     "routed to the infra-manager/responder path (fleet-sysadmin role)."),
]

# The role authority model — mirrored from docs/roles/README.md's role map
# + the authority rules proven in code (responder approval gate, tier2
# supervisory-only rule, router-as-infra-authority).
ROLES = [
    ("Router", "Classifies every alert via the single categorizer, applies "
     "noise/dedupe/tuning gates, routes to the owning role. Approving "
     "authority for INFRA cases only (tier0/1; never tier2)."),
    ("Analyst", "First verdict: note | escalate. Attaches observables + "
     "enrichments; recommends playbooks (tier1/2 enrichment hook)."),
    ("Investigator", "Correlates the entity across sources; produces "
     "severity (log-count + kill-chain breadth) and evidence."),
    ("Supervisory", "Approve | deny. The verdict AUTHORITY for security "
     "cases; writes the tuning ledger (deny -> auto_fp with fingerprint). "
     "Sole authority for tier2 run_id approval."),
    ("Responder", "Executes playbooks under the tier model. tier0/1 "
     "execute on trigger+recommendation; tier2 requires a supervisory "
     "run_id (expires in 15 min). Router adjudication authorizes tier0/1 "
     "on infra cases; NEVER tier2."),
    ("Hunt", "Hypothesis-driven sweeps; findings escalate with playbook "
     "recommendations; consumes MISP bulk feed matching (local corpus "
     "first, external lookups on survivors only)."),
    ("Intel", "Matches KEV/NVD feeds into hunt packs; stages, never "
     "promotes."),
    ("InfraManager", "Self-heal: senses fleet health, fixes whitelisted "
     "issues, escalates the rest."),
]

TIERS = [
    ("tier0", "Execute immediately, no approval (verify/known-safe)."),
    ("tier1", "Execute immediately on trigger + recommendation, recorded."),
    ("tier2", "Escalation ticket with run_id + expiry (15 min). Human "
     "approval matching the run_id required; supervisory-only."),
]


def render() -> str:
    L: list[str] = [PREFIXES, ""]
    L.append(f"<http://ssop.local/ontology> a owl:Ontology ;\n"
             f"    rdfs:label \"SSOP decision ontology\" ;\n"
             f"    rdfs:comment \"Machine-readable statement of the SSOP "
             f"role/authority/decision model. GENERATED by "
             f"agents/tools/ontology_export.py — do not hand-edit. "
             f"Phase 2 (check_ontology) runs a reasoner over this.\" .\n")

    L.append("## ---- core classes ----\n")
    for cls, comment in [
        ("Alert", "A normalized SIEM alert (alert contract, issue #25)."),
        ("Observable", "An extracted indicator: ip | hash | domain | url."),
        ("Case", "A spine case (event-point store, dual-written)."),
        ("Verdict", "A role's classification of an alert/case."),
        ("Decision", "An authority's approve/deny with rationale."),
        ("Playbook", "A whitelisted action sequence under the tier model."),
        ("TuningEntry", "A durable human tuning decision (fingerprint + "
         "optional exclude_hosts)."),
        ("Receipt", "An append-only spine/audit event."),
    ]:
        L.append(f":{cls} a owl:Class ;\n    rdfs:comment \"{comment}\" .\n")

    L.append("## ---- role classes (each a:Role) ----\n")
    L.append(":Role a owl:Class .\n")
    for role, comment in ROLES:
        L.append(f":{role} a owl:Class ;\n    rdfs:subClassOf :Role ;\n"
                 f"    rdfs:comment \"{comment}\" .\n")

    L.append("## ---- alert category classes ----\n")
    L.append(":AlertCategory a owl:Class .\n")
    for cat, comment in CATEGORIES:
        L.append(f":{cat} a owl:Class ;\n    rdfs:subClassOf :AlertCategory ;\n"
                 f"    rdfs:comment \"{comment}\" .\n")

    L.append("## ---- approval tiers ----\n")
    L.append(":Tier a owl:Class .\n")
    for tier, comment in TIERS:
        L.append(f":{tier} a owl:Class ;\n    rdfs:subClassOf :Tier ;\n"
                 f"    rdfs:comment \"{comment}\" .\n")

    L.append("## ---- object properties ----\n")
    for prop, dom, rng, comment in [
        ("classifiedAs", "Alert", "AlertCategory",
         "Exactly one category per alert (single categorizer)."),
        ("ownedBy", "Alert", "Role", "Dispatch: the owning role."),
        ("hasObservable", "Case", "Observable", ""),
        ("hasVerdict", "Alert", "Verdict", ""),
        ("hasDecision", "Case", "Decision", ""),
        ("approvedBy", "Decision", "Role",
         "supervisory for security cases; router for infra cases (tier0/1)."),
        ("executes", "Responder", "Playbook", "tier0/1 on trigger+rec."),
        ("requiresApprovalFrom", "Playbook", "Role",
         "tier2 -> Supervisory (run_id + expiry)."),
        ("tunesRule", "TuningEntry", "Alert",
         "Fingerprint-keyed; material delta overrides."),
    ]:
        L.append(f":{prop} a owl:ObjectProperty ;\n    rdfs:domain :{dom} ;\n"
                 f"    rdfs:range :{rng} ;\n"
                 + (f"    rdfs:comment \"{comment}\" .\n" if comment else " .\n"))

    L.append("## ---- authority invariants (axioms; phase 2 proves) ----\n")
    # Machine-checkable authority axioms (phase 2 = verify/check_ontology.py
    # runs HermiT over these; see the design note at the top of that file).
    # Tier2 decisions are approved by SUPERVISORY ONLY: allValuesFrom makes
    # every approvedBy filler of a Tier2 decision a Supervisory instance.
    # Role disjointness then makes a Router-instance filler a contradiction —
    # which is exactly the operator policy "router never authorizes tier2".
    # The reasoner only bites when the filler is a named INDIVIDUAL of class
    # Router (a class IRI used as a property value punns as an individual and
    # HermiT ignores class disjointness for it) — the check's probes do that.
    L.append(
        ":Tier2 a owl:Class ;\n"
        "    rdfs:subClassOf :Tier ,\n"
        "        [ a owl:Restriction ;\n"
        "          owl:onProperty :approvedBy ;\n"
        "          owl:allValuesFrom :Supervisory ] .\n"
        "\n"
        "# Approving-authority roles are pairwise disjoint: a thing approved\n"
        "# by Router is NOT approved by Supervisory (and vice versa).\n"
        "[] a owl:AllDisjointClasses ;\n"
        "    owl:members ( :Supervisory :Router ) .\n"
        "\n"
        "# Router never authorizes tier2 (operator policy 2026-09-09) is the\n"
        "# composition of the two axioms above: Tier2 -> approvedBy only\n"
        "# Supervisory, and Supervisory disjointWith Router. verify/\n"
        "# check_ontology.py proves it by feeding a Router-individual-approved\n"
        "# Tier2 decision to the reasoner and requiring inconsistency, plus a\n"
        "# positive control (Supervisory-approved stays consistent).\n"
        "# responder-executed case implies a Decision exists with approvedBy\n"
        "# in {Supervisory, Router}.\n")
    return "\n".join(L)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print("ONTOLOGY EXPORT DRIFT: docs/ontology/ssop.ttl is stale — "
                  "rerun agents/tools/ontology_export.py", file=sys.stderr)
            return 1
        print("ontology export: up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(f"wrote {OUT} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
